org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
# ============================================================
# TẠM TẮT KOTLIN INCREMENTAL CACHE
# để xử lý lỗi "Could not close incremental caches"
# ============================================================

kotlin.incremental=false
# kotlin.incremental.useClasspathSnapshot=false

# Cho Kotlin compiler chạy trong cùng process Gradle
kotlin.compiler.execution.strategy=in-process

# Tạm tắt Gradle cache để tránh dùng lại cache lỗi
org.gradle.caching=false

# Tạm tắt daemon để test build sạch
org.gradle.daemon=false