// Extracted from template 376. See docs/xn-tra-sau-api/gpb_376_template.json.
class XnGpb376Field {
  const XnGpb376Field(
    this.name,
    this.label,
    this.group, {
    this.bold = false,
    this.italic = false,
  });
  final String name, label, group;
  final bool bold, italic;
}

const xnGpb376Fields = <XnGpb376Field>[
  XnGpb376Field("dgtbdat", "Đạt", "assessment", bold: true, italic: false),
  XnGpb376Field(
    "dgtbkhongdat",
    "Không đạt",
    "assessment",
    bold: true,
    italic: false,
  ),
  XnGpb376Field(
    "tthnoibieumoactinh",
    "ÂM TÍNH VỚI TỔN THƯƠNG NỘI BIỂU MÔ HOẶC ÁC TÍNH",
    "negative",
    bold: true,
    italic: false,
  ),
  XnGpb376Field(
    "bdoitbkhongu",
    "CÁC BIẾN ĐỔI TẾ BÀO KHÔNG U",
    "non_neoplastic",
    bold: true,
    italic: false,
  ),
  XnGpb376Field(
    "dsvay",
    "Dị sản vảy",
    "non_neoplastic",
    bold: false,
    italic: true,
  ),
  XnGpb376Field(
    "bdsung",
    "Biến đổi sừng",
    "non_neoplastic",
    bold: false,
    italic: true,
  ),
  XnGpb376Field(
    "tbttucung",
    "Tế bào tuyến sau cắt tử cung",
    "non_neoplastic",
    bold: false,
    italic: true,
  ),
  XnGpb376Field("cboxteo", "Teo", "non_neoplastic", bold: false, italic: true),
  XnGpb376Field(
    "lqnoitiet",
    "Liên quan đến nội tiết",
    "non_neoplastic",
    bold: false,
    italic: true,
  ),
  XnGpb376Field(
    "cbvisinhvat",
    "VIÊM DO VI SINH VẬT",
    "infection",
    bold: true,
    italic: false,
  ),
  XnGpb376Field(
    "TVaginalis",
    "T. Vaginalis",
    "infection",
    bold: false,
    italic: true,
  ),
  XnGpb376Field(
    "cbVaginalis",
    "G. Vaginalis",
    "infection",
    bold: false,
    italic: true,
  ),
  XnGpb376Field(
    "Actinomyces",
    "Actinomyces",
    "infection",
    bold: false,
    italic: false,
  ),
  XnGpb376Field(
    "namCandida",
    "Nấm Candida",
    "infection",
    bold: false,
    italic: true,
  ),
  XnGpb376Field(
    "Herpessimplex",
    "Herpes simplex virus",
    "infection",
    bold: false,
    italic: true,
  ),
  XnGpb376Field("cbHPV", "HPV", "infection", bold: false, italic: true),
  XnGpb376Field(
    "tuyennoimac",
    "TẾ BÀO TUYẾN NỘI MẠC NGOÀI KỲ KINH Ở PHỤ NỮ ≥ 45 TUỔI",
    "endometrial",
    bold: true,
    italic: false,
  ),
  XnGpb376Field(
    "btgbieumo",
    "BẤT THƯỜNG BIỂU MÔ",
    "epithelial",
    bold: true,
    italic: false,
  ),
  XnGpb376Field(
    "btgbieumovay",
    "BẤT THƯỜNG BIỂU MÔ VẢY",
    "squamous",
    bold: true,
    italic: false,
  ),
  XnGpb376Field(
    "btgmotuyen",
    "BẤT THƯỜNG BIỂU MÔ TUYẾN",
    "glandular",
    bold: true,
    italic: false,
  ),
  XnGpb376Field(
    "btgbieumovay1",
    "TB biểu mô vảy không điển hình (ASCUS)",
    "squamous",
    bold: false,
    italic: true,
  ),
  XnGpb376Field(
    "btgmotuyen1",
    "TB biểu mô tuyến không điển hình (AGUS)",
    "glandular",
    bold: false,
    italic: true,
  ),
  XnGpb376Field(
    "btgbieumovay2",
    "TB biểu mô vảy không điển hình, chưa loại trừ HSIL (ASC-H",
    "squamous",
    bold: false,
    italic: true,
  ),
  XnGpb376Field(
    "btgmotuyen2",
    "TB tuyến không điển hình liên quan tân sản",
    "glandular",
    bold: false,
    italic: true,
  ),
  XnGpb376Field(
    "btgbieumovay3",
    "Tổn thương tế bào nội biểu mô vảy độ thấp (LSIL)",
    "squamous",
    bold: false,
    italic: true,
  ),
  XnGpb376Field(
    "btgmotuyen3",
    "Ung thư tế bào biểu mô tuyến tại chỗ",
    "glandular",
    bold: false,
    italic: true,
  ),
  XnGpb376Field(
    "btgbieumovay4",
    "Tổn thương tế bào nội biểu mô vảy độ cao (HSIL)",
    "squamous",
    bold: false,
    italic: true,
  ),
  XnGpb376Field(
    "btgmotuyen4",
    "Ung thư tế bào biểu mô tuyến",
    "glandular",
    bold: false,
    italic: true,
  ),
  XnGpb376Field(
    "btgbieumovay5",
    "Tổn thương HSIL với các đặc điểm nghi ngờ xâm nhập",
    "squamous",
    bold: false,
    italic: true,
  ),
  XnGpb376Field("btgmotuyen5", "Khác", "glandular", bold: false, italic: true),
  XnGpb376Field(
    "btgbieumovay6",
    "Ung thư tế bào biểu mô vảy",
    "squamous",
    bold: false,
    italic: true,
  ),
  XnGpb376Field(
    "Uactinhkhac",
    "U ÁC TÍNH KHÁC",
    "other",
    bold: true,
    italic: false,
  ),
];
final xnGpb376Labels = Map<String, String>.unmodifiable({
  for (final field in xnGpb376Fields) field.name.toLowerCase(): field.label,
});
