import 'xn_gpb_376_template.dart';

typedef XnRow = Map<String, dynamic>;

// HIS returns dictionary keys with mixed casing. Do not change value types.
dynamic xnValue(XnRow row, String key) {
  for (final entry in row.entries) {
    if (entry.key.toLowerCase() == key.toLowerCase()) return entry.value;
  }
  return null;
}

String xnText(dynamic value) => value?.toString().trim() ?? '';

int? xnInt(dynamic value) => int.tryParse(xnText(value));

bool? xnBool(dynamic value) {
  if (value is bool) return value;
  switch (xnText(value).toLowerCase()) {
    case 'true':
    case '1':
      return true;
    case 'false':
    case '0':
      return false;
    default:
      return null;
  }
}

List<XnRow> xnRows(dynamic value) {
  if (value is Map) return [Map<String, dynamic>.from(value)];
  if (value is! List) return [];
  return value
      .whereType<Map>()
      .map((e) => Map<String, dynamic>.from(e))
      .toList();
}

final _hisFormatDirective = RegExp(
  r'<(?:fn[^<>]*|fs\d+(?:\.\d+)?|fc\s*\d{1,3}\s*,\s*\d{1,3}\s*,\s*\d{1,3}|/?b|/?i|/?u)>',
  caseSensitive: false,
);

String _normalizeXnText(dynamic value) {
  final text = xnText(value);
  return text
      .replaceAll('\r\n', '\n')
      .replaceAll('\r', '\n')
      .replaceAll('\u2028', '\n')
      .replaceAll('\u2029', '\n')
      .replaceAll(
        RegExp(r'[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F]'),
        '',
      );
}

// Remove only known HIS directives. Comparisons such as <5 are data and must
// remain unchanged.
String xnDisplayText(dynamic value) =>
    _normalizeXnText(value).replaceAll(_hisFormatDirective, '').trim();

class XnFormattedText {
  const XnFormattedText({
    required this.text,
    this.bold = false,
    this.italic = false,
    this.underline = false,
    this.red,
    this.green,
    this.blue,
  });

  final String text;
  final bool bold;
  final bool italic;
  final bool underline;
  final int? red;
  final int? green;
  final int? blue;

  bool get hasColor => red != null && green != null && blue != null;
}

// fnFormatResult returns values such as:
// <fc255,0,0><fnTimes New Roman><fs12><b>12.11
// Keep the raw result text from ketqua_goc, but inherit presentation from the
// formatted ketluan field generated by HIS.
XnFormattedText xnFormattedText(dynamic formatted, {dynamic fallbackText}) {
  final source = _normalizeXnText(formatted);
  final color = RegExp(
    r'<fc\s*(\d{1,3})\s*,\s*(\d{1,3})\s*,\s*(\d{1,3})>',
    caseSensitive: false,
  ).firstMatch(source);
  final bracketColor = RegExp(
    r'^\[(\d{1,3})\]\[(\d{1,3})\]\[(\d{1,3})\]',
  ).firstMatch(source);
  final match = color ?? bracketColor;
  int? channel(int group) {
    final value = int.tryParse(match?.group(group) ?? '');
    return value?.clamp(0, 255).toInt();
  }

  final fallback = xnDisplayText(fallbackText);
  final plain = xnDisplayText(source).replaceFirst(
    RegExp(r'^\[\d{1,3}\]\[\d{1,3}\]\[\d{1,3}\]'),
    '',
  );
  return XnFormattedText(
    text: fallback.isNotEmpty ? fallback : plain,
    bold: RegExp(r'<b>', caseSensitive: false).hasMatch(source),
    italic: RegExp(r'<i>', caseSensitive: false).hasMatch(source),
    underline: RegExp(r'<u>', caseSensitive: false).hasMatch(source),
    red: channel(1),
    green: channel(2),
    blue: channel(3),
  );
}

enum XnResultKind {
  laboratory('XET_NGHIEM', 'xet-nghiem', 'Xét nghiệm'),
  pathology('GPB', 'gpb', 'Giải phẫu bệnh'),
  antibiogram('KHANG_SINH_DO', 'khang-sinh-do', 'Kháng sinh đồ');

  const XnResultKind(this.code, this.route, this.label);
  final String code;
  final String route;
  final String label;

  static XnResultKind? parse(dynamic value) {
    for (final kind in values) {
      if (kind.code == xnText(value)) return kind;
    }
    return null;
  }
}

class XnResultTemplate {
  const XnResultTemplate(this.id, this.kind);
  final String id;
  final XnResultKind? kind;
}

class XnResultConfig {
  XnResultConfig.fromJson(this.data)
    : id = xnInt(xnValue(data, 'id')),
      detailId = xnInt(xnValue(data, 'mathanhtoanct')),
      usesV2 = xnBool(xnValue(data, 'suDungKetQuaKhacV2')) == true,
      templates = xnRows(xnValue(data, 'danhSachMau'))
          .map(
            (e) => XnResultTemplate(
              xnText(xnValue(e, 'idMauIn')),
              XnResultKind.parse(xnValue(e, 'loaiKetQua')),
            ),
          )
          .where((e) => e.id.isNotEmpty)
          .toList(),
      forms = xnRows(xnValue(data, 'danhSachForm'))
          .map((e) => xnInt(xnValue(e, 'idForm')))
          .whereType<int>()
          .where((e) => e > 0)
          .toSet()
          .toList();

  final XnRow data;
  final int? id;
  final int? detailId;
  final bool usesV2;
  final List<XnResultTemplate> templates;
  final List<int> forms;
}

class XnResultException implements Exception {
  const XnResultException(this.message, {this.code});
  final String message;
  final String? code;
  @override
  String toString() => message;
}

// Keep organism identity; names alone are not unique.
bool xnSameOrganism(XnRow a, XnRow b) =>
    xnText(xnValue(a, 'vikhuanid')) == xnText(xnValue(b, 'vikhuanid')) &&
    xnText(xnValue(a, 'mavikhuan')) == xnText(xnValue(b, 'mavikhuan'));

// Each print template can have a different layout even within GPB.
class XnGpbLayout {
  const XnGpbLayout(
    this.title,
    this.resultLabels, {
    this.fieldLabels = const {},
  });
  final String title;
  final Map<String, String> resultLabels;
  final Map<String, String> fieldLabels;
}

XnGpbLayout xnGpbLayout(String template, int? form) {
  if (template == '376' && form == 12) {
    return XnGpbLayout('Kết quả tế bào học cổ tử cung · Thin Prep', {
      'ketluan': 'Kết luận',
      'mota': 'Mô tả',
      'docketqua': 'Nội dung bổ sung',
    }, fieldLabels: xnGpb376Labels);
  }
  if (template == '381' && form == null) {
    return const XnGpbLayout('Kết quả mô bệnh học', {
      'docketqua': 'Đại thể',
      'mota': 'Vi thể',
      'ketluan': 'Kết luận',
    });
  }
  if (template == '383' && form == null) {
    return const XnGpbLayout('Kết quả tế bào học', {
      'mota': 'Mô tả tế bào học',
      'docketqua': 'Nội dung bổ sung',
      'ketluan': 'Kết luận',
    });
  }
  return const XnGpbLayout('Kết quả giải phẫu bệnh', {
    'mota': 'Mô tả',
    'docketqua': 'Nội dung bổ sung',
    'ketluan': 'Kết luận',
  });
}
