// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF0cTTVMPcx27OXCK5yv5P2vu6zC9wooM',
    appId: '1:413550551562:web:4ff3969e3f6bfc4cd8f5f3',
    messagingSenderId: '413550551562',
    projectId: 'hrm-hung-vuong',
    authDomain: 'hrm-hung-vuong.firebaseapp.com',
    storageBucket: 'hrm-hung-vuong.firebasestorage.app',
    measurementId: 'G-9BYXCS8YJQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsIED7r7CAxDgNsGIidIUpmHJs6K-o6NI',
    appId: '1:413550551562:android:b68f546f3b2579d5d8f5f3',
    messagingSenderId: '413550551562',
    projectId: 'hrm-hung-vuong',
    storageBucket: 'hrm-hung-vuong.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwnJ8oNwPuLbbBMZ0A53_ncAJZMNELRJ4',
    appId: '1:413550551562:ios:5429a2e84c2ae920d8f5f3',
    messagingSenderId: '413550551562',
    projectId: 'hrm-hung-vuong',
    storageBucket: 'hrm-hung-vuong.firebasestorage.app',
    iosBundleId: 'com.myhungvuong.mobileappbvhv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwnJ8oNwPuLbbBMZ0A53_ncAJZMNELRJ4',
    appId: '1:413550551562:ios:648ba04eb6ece501d8f5f3',
    messagingSenderId: '413550551562',
    projectId: 'hrm-hung-vuong',
    storageBucket: 'hrm-hung-vuong.firebasestorage.app',
    iosBundleId: 'com.example.mobileappBvhv',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCF0cTTVMPcx27OXCK5yv5P2vu6zC9wooM',
    appId: '1:413550551562:web:fd5ffd0ba3ed84f1d8f5f3',
    messagingSenderId: '413550551562',
    projectId: 'hrm-hung-vuong',
    authDomain: 'hrm-hung-vuong.firebaseapp.com',
    storageBucket: 'hrm-hung-vuong.firebasestorage.app',
    measurementId: 'G-KBQBP8SK3P',
  );
}
